stages:
  - test
  - upload_results

playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.49.0-noble
  script:
    - npm ci
    - npx playwright install chromium
    - npx playwright test
  artifacts:
    when: always
    paths:
      - test-results/junit-report.xml
      - playwright-report/
    expire_in: 4 days

upload_zephyr_results:
  stage: upload_results
  image: ubuntu:20.04
  dependencies:
    - playwright_tests
  before_script:
    - apt-get update && apt-get install -y curl jq
  script:
    - |
      for TEST_CASE in $(jq -r '.testsuites[] | .testsuite[] | .testcase | select(.name | contains("[TEST-T")) | .name' test-results/junit-report.xml); do
        TEST_KEY=$(echo "$TEST_CASE" | grep -oP '(?<=TEST-)[A-Z0-9-]+')
        STATUS=$(jq -r --arg name "$TEST_CASE" '.testsuites[] | .testsuite[] | .testcase | select(.name == $name) | if .failure then "Fail" else "Pass" end' test-results/junit-report.xml)
        EXECUTION_TIME=$(jq -r --arg name "$TEST_CASE" '.testsuites[] | .testsuite[] | .testcase | select(.name == $name) | .["@time"]' test-results/junit-report.xml | awk '{print int($1 * 1000)}')

        curl -s -X POST \
          -H "Authorization: Bearer $ZEPHYR_AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          "https://api.zephyrscale.smartbear.com/v2/testexecutions" \
          -d "{
            \"projectKey\": \"TEST\",
            \"testCaseKey\": \"TEST-$TEST_KEY\",
            \"testCycleKey\": \"TEST-R4\",
            \"statusName\": \"$STATUS\",
            \"environmentName\": \"chromium\",
            \"actualEndDate\": \"2025-04-29T04:30:00Z\",
            \"executionTime\": $EXECUTION_TIME,
            \"comment\": \"Automated test executed via GitLab CI\"
          }"
      done