stages:
  - test
  - upload_results

playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.49.0-noble
  script:
    - npm ci
    - npx playwright install chromium
    - npx playwright test
  artifacts:
    when: always
    paths:
      - test-results/junit-report.xml
      - playwright-report/
    expire_in: 4 days

upload_zephyr_results:
  stage: upload_results
  image: ubuntu:20.04
  dependencies:
    - playwright_tests
  before_script:
    - apt-get update && apt-get install -y curl xmlstarlet bc
  script:
    - |
      xmlstarlet sel -t -m "//testcase[contains(@name, '[TEST-T')]" \
        -v "substring-before(substring-after(@name, '[TEST-'), ']')" -o "|" \
        -i "count(failure)=0" -o "Pass" -b -i "count(failure)>0" -o "Fail" -b -o "|" \
        -v "@time" -n test-results/junit-report.xml | while IFS='|' read -r test_key status time; do
        [ -z "$test_key" ] && continue
        execution_time=$(echo "$time * 1000" | bc | awk '{print int($1)}')
        [ -z "$execution_time" ] && execution_time=0
        response=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Authorization: Bearer $ZEPHYR_AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          "https://api.zephyrscale.smartbear.com/v2/testexecutions" \
          -d "{
            \"projectKey\": \"TEST\",
            \"testCaseKey\": \"TEST-$test_key\",
            \"testCycleKey\": \"TEST-R5\",
            \"statusName\": \"$status\",
            \"environmentName\": \"chromium\",
            \"actualEndDate\": \"2025-04-29T10:04:07Z\",
            \"executionTime\": $execution_time,
            \"comment\": \"Automated test executed via GitLab CI\"
          }")
        http_code=$(echo "$response" | tail -n1)
        [ "$http_code" -ne 201 ] && exit 1
      done