stages:
  - test
  - upload_results

playwright_tests:
  stage: test
  image: mcr.microsoft.com/playwright:v1.49.0-noble
  script:
    - npm ci
    - npx playwright install chromium
    - mkdir -p test-results
    - npx playwright test --reporter=junit
  artifacts:
    when: always
    paths:
      - test-results/junit-report.xml
      - playwright-report/
    expire_in: 4 days

upload_zephyr_results:
  stage: upload_results
  image: ubuntu:20.04
  dependencies:
    - playwright_tests
  before_script:
    - apt-get update && apt-get install -y curl xmlstarlet bc
  script:
    - |
      if [ ! -f "test-results/junit-report.xml" ]; then exit 1; fi
      xmlstarlet sel -t -m "//testcase[contains(@name, '[TEST-T')]" \
        -v "substring-before(substring-after(@name, '[TEST-'), ']')" -o "|" \
        -i "count(failure)=0" -o "Pass" -b -i "count(failure)>0" -o "Fail" -b -o "|" \
        -v "@time" -n test-results/junit-report.xml > parsed_tests.txt
      if [ ! -s parsed_tests.txt ]; then exit 0; fi
      while IFS='|' read -r test_key status time; do
        if [ -z "$test_key" ]; then continue; fi
        execution_time=$(echo "$time * 1000" | bc | awk '{print int($1)}')
        if [ -z "$execution_time" ]; then execution_time=0; fi
        current_time=$(date -u +"%Y-%m-%dT%H:%M:%SZ")
        response=$(curl -s -w "\n%{http_code}" -X POST \
          -H "Authorization: Bearer $ZEPHYR_AUTH_TOKEN" \
          -H "Content-Type: application/json" \
          "https://api.zephyrscale.smartbear.com/v2/testexecutions" \
          -d "{
            \"projectKey\": \"TEST\",
            \"testCaseKey\": \"TEST-$test_key\",
            \"testCycleKey\": \"TEST-R5\",
            \"statusName\": \"$status\",
            \"environmentName\": \"chromium\",
            \"actualEndDate\": \"$current_time\",
            \"executionTime\": $execution_time,
            \"comment\": \"Automated test executed via GitLab CI\"
          }")
        if [ "$(printf '%s' "$response" | tail -n1)" -ne 201 ]; then exit 1; fi
      done < parsed_tests.txt